package me.hbu.frank.archives;


/**
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
 */
public class Problem012 {

	public static void main(String[] args) {
		long divisors = 0;
		long current = 0; 
		int i = 1;
		while (divisors < 500) {
			current += i;
			divisors = getDivisorsCount(current);
			i++;
		}
		System.out.println(current);
	}

	private static long getDivisorsCount(long current) {
		int count = 0;
		for (long i = 1; i <= Math.sqrt(current); i++) {
			if (current % i == 0) {
				long j = current / i;
				if (i != j) {
					count ++;
				}
				count ++;
			}
		}
		count ++;
		return count;
	}

}
